package com.jop.hibernate.dto;
// Generated 18-jul-2018 15:11:41 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos implements java.io.Serializable {

	// PROPIEDADES DE CLASE **********************************************
	private static final long serialVersionUID = 410446576720306983L;
	private int codigoArticulo;
	private String descripcionArticulo;
	private BigDecimal precioUnidadArticulo;
	private Integer cantidad;
	private Set<LineaPedido> lineaPedidos = new HashSet<>(0);

	// CONSTRUCTORES *****************************************************
	public Articulos() {
	}

	public Articulos(int codigoArticulo) {
		this.codigoArticulo = codigoArticulo;
	}

	public Articulos(int codigoArticulo, String descripcionArticulo, BigDecimal precioUnidadArticulo, Integer cantidad,
			Set<LineaPedido> lineaPedidos) {
		this.codigoArticulo = codigoArticulo;
		this.descripcionArticulo = descripcionArticulo;
		this.precioUnidadArticulo = precioUnidadArticulo;
		this.cantidad = cantidad;
		this.lineaPedidos = lineaPedidos;
	}

	// ACCESORES *********************************************************
	public int getCodigoArticulo() {
		return this.codigoArticulo;
	}

	public void setCodigoArticulo(int codigoArticulo) {
		this.codigoArticulo = codigoArticulo;
	}

	public String getDescripcionArticulo() {
		return this.descripcionArticulo;
	}

	public void setDescripcionArticulo(String descripcionArticulo) {
		this.descripcionArticulo = descripcionArticulo;
	}

	public BigDecimal getPrecioUnidadArticulo() {
		return this.precioUnidadArticulo;
	}

	public void setPrecioUnidadArticulo(BigDecimal precioUnidadArticulo) {
		this.precioUnidadArticulo = precioUnidadArticulo;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Set getLineaPedidos() {
		return this.lineaPedidos;
	}

	public void setLineaPedidos(Set<LineaPedido> lineaPedidos) {
		this.lineaPedidos = lineaPedidos;
	}

	@Override
	public String toString() {
		return "Articulos [codigoArticulo=" + codigoArticulo + ", descripcionArticulo=" + descripcionArticulo
				+ ", precioUnidadArticulo=" + precioUnidadArticulo + ", cantidad=" + cantidad + "]";
	}

}
