package com.jop.hibernate.dto;
// Generated 18-jul-2018 15:11:41 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * LineaPedido generated by hbm2java
 */
public class LineaPedido implements java.io.Serializable {

	// PROPIEDADES DE CLASE **********************************************
	private static final long serialVersionUID = 7525859947293433323L;
	private long codigoLineaPedido;
	private Pedidos pedido;
	private Articulos articulos;
	private BigDecimal precioUnidadArticulo;
	private Integer numeroUnidadesArticulo;
	private BigDecimal porcentajeDescuento;

	// CONSTRUCTORES *****************************************************
	public LineaPedido() {
	}

	public LineaPedido(long codigoLineaPedido) {
		this.codigoLineaPedido = codigoLineaPedido;
	}

	public LineaPedido(Pedidos pedido, Articulos articulos, Integer numeroUnidadesArticulo) {
		this.pedido = pedido;
		this.articulos = articulos;
		this.numeroUnidadesArticulo = numeroUnidadesArticulo;
	}

	public LineaPedido(long codigoLineaPedido, Pedidos pedido, Articulos articulos, BigDecimal precioUnidadArticulo,
			Integer numeroUnidadesArticulo, BigDecimal porcentajeDescuento) {
		this.codigoLineaPedido = codigoLineaPedido;
		this.pedido = pedido;
		this.articulos = articulos;
		this.precioUnidadArticulo = precioUnidadArticulo;
		this.numeroUnidadesArticulo = numeroUnidadesArticulo;
		this.porcentajeDescuento = porcentajeDescuento;
	}

	// ACCESORES *********************************************************
	public long getCodigoLineaPedido() {
		return this.codigoLineaPedido;
	}

	public void setCodigoLineaPedido(long codigoLineaPedido) {
		this.codigoLineaPedido = codigoLineaPedido;
	}

	public Pedidos getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedidos pedido) {
		this.pedido = pedido;
	}

	public Articulos getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Articulos articulos) {
		this.articulos = articulos;
	}

	public BigDecimal getPrecioUnidadArticulo() {
		return this.precioUnidadArticulo;
	}

	public void setPrecioUnidadArticulo(BigDecimal precioUnidadArticulo) {
		this.precioUnidadArticulo = precioUnidadArticulo;
	}

	public Integer getNumeroUnidadesArticulo() {
		return this.numeroUnidadesArticulo;
	}

	public void setNumeroUnidadesArticulo(Integer numeroUnidadesArticulo) {
		this.numeroUnidadesArticulo = numeroUnidadesArticulo;
	}

	public BigDecimal getPorcentajeDescuento() {
		return this.porcentajeDescuento;
	}

	public void setPorcentajeDescuento(BigDecimal porcentajeDescuento) {
		this.porcentajeDescuento = porcentajeDescuento;
	}

	// OTROS METODOS *****************************************************
	@Override
	public String toString() {
		return "LineaPedido [codigoLineaPedido=" + codigoLineaPedido + ", pedido=" + pedido + ", articulos=" + articulos
				+ ", precioUnidadArticulo=" + precioUnidadArticulo + ", numeroUnidadesArticulo="
				+ numeroUnidadesArticulo + ", porcentajeDescuento=" + porcentajeDescuento + "]";
	}

}
