package com.jop.hibernate.dto;
// Generated 18-jul-2018 15:11:41 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos implements java.io.Serializable {

	// PROPIEDADES DE CLASE **********************************************
	private static final long serialVersionUID = -6329896219043020644L;
	private int numeroPedido;
	private Date fechaPedido;
	private BigDecimal portePedido;
	private BigDecimal seguroPedido;
	private BigDecimal otrosCargosPedido;
	private BigDecimal totalCargosPedido;
	private BigDecimal totalBrutoPedido;
	private Byte porcentajeIvaPedido;
	private BigDecimal ivaPedido;
	private BigDecimal totalFacturaPedido;
	private int codigoCliente;
	private Set<LineaPedido> lineaPedidos = new HashSet<>(0);

	// CONSTRUCTORES *****************************************************
	public Pedidos() {
	}

	public Pedidos(int numeroPedido, int codigoCliente) {
		this.numeroPedido = numeroPedido;
		this.codigoCliente = codigoCliente;
	}

	public Pedidos(int numeroPedido, Date fechaPedido, BigDecimal portePedido, BigDecimal seguroPedido,
			BigDecimal otrosCargosPedido, BigDecimal totalCargosPedido, BigDecimal totalBrutoPedido,
			Byte porcentajeIvaPedido, BigDecimal ivaPedido, BigDecimal totalFacturaPedido, int codigoCliente,
			Set<LineaPedido> lineaPedidos) {
		this.numeroPedido = numeroPedido;
		this.fechaPedido = fechaPedido;
		this.portePedido = portePedido;
		this.seguroPedido = seguroPedido;
		this.otrosCargosPedido = otrosCargosPedido;
		this.totalCargosPedido = totalCargosPedido;
		this.totalBrutoPedido = totalBrutoPedido;
		this.porcentajeIvaPedido = porcentajeIvaPedido;
		this.ivaPedido = ivaPedido;
		this.totalFacturaPedido = totalFacturaPedido;
		this.codigoCliente = codigoCliente;
		this.lineaPedidos = lineaPedidos;
	}

	// ACCESORES *********************************************************
	public int getNumeroPedido() {
		return this.numeroPedido;
	}

	public void setNumeroPedido(int numeroPedido) {
		this.numeroPedido = numeroPedido;
	}

	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public BigDecimal getPortePedido() {
		return this.portePedido;
	}

	public void setPortePedido(BigDecimal portePedido) {
		this.portePedido = portePedido;
	}

	public BigDecimal getSeguroPedido() {
		return this.seguroPedido;
	}

	public void setSeguroPedido(BigDecimal seguroPedido) {
		this.seguroPedido = seguroPedido;
	}

	public BigDecimal getOtrosCargosPedido() {
		return this.otrosCargosPedido;
	}

	public void setOtrosCargosPedido(BigDecimal otrosCargosPedido) {
		this.otrosCargosPedido = otrosCargosPedido;
	}

	public BigDecimal getTotalCargosPedido() {
		return this.totalCargosPedido;
	}

	public void setTotalCargosPedido(BigDecimal totalCargosPedido) {
		this.totalCargosPedido = totalCargosPedido;
	}

	public BigDecimal getTotalBrutoPedido() {
		return this.totalBrutoPedido;
	}

	public void setTotalBrutoPedido(BigDecimal totalBrutoPedido) {
		this.totalBrutoPedido = totalBrutoPedido;
	}

	public Byte getPorcentajeIvaPedido() {
		return this.porcentajeIvaPedido;
	}

	public void setPorcentajeIvaPedido(Byte porcentajeIvaPedido) {
		this.porcentajeIvaPedido = porcentajeIvaPedido;
	}

	public BigDecimal getIvaPedido() {
		return this.ivaPedido;
	}

	public void setIvaPedido(BigDecimal ivaPedido) {
		this.ivaPedido = ivaPedido;
	}

	public BigDecimal getTotalFacturaPedido() {
		return this.totalFacturaPedido;
	}

	public void setTotalFacturaPedido(BigDecimal totalFacturaPedido) {
		this.totalFacturaPedido = totalFacturaPedido;
	}

	public int getCodigoCliente() {
		return this.codigoCliente;
	}

	public void setCodigoCliente(int codigoCliente) {
		this.codigoCliente = codigoCliente;
	}

	public Set getLineaPedidos() {
		return this.lineaPedidos;
	}

	public void setLineaPedidos(Set<LineaPedido> lineaPedidos) {
		this.lineaPedidos = lineaPedidos;
	}

	@Override
	public String toString() {
		return "Pedidos [numeroPedido=" + numeroPedido + ", fechaPedido=" + fechaPedido + ", codigoCliente=" + codigoCliente + "]";
	}


}
